### Exploration over [dataset](./data/dataset.csv) of breast cancer gene (BRCG)

In [35]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [36]:
pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_rows', 1000)

In [37]:
df = pd.read_csv("./data/dataset.csv", sep='\t')

df.columns = df.columns.str.replace(r'\xa0', ' ', regex=True).str.strip()

pd.concat([df.head(10), df.tail(10)])

,CHROM,POS,REF,ALT,Interpro_domain,dbNSFP_DEOGEN2_pred,dbNSFP_MetaSVM_pred,dbNSFP_fathmmMKL_coding_pred,dbNSFP_PrimateAI_pred,dbNSFP_PROVEAN_pred,dbNSFP_MCAP_pred,dbNSFP_ClinPred_pred,dbNSFP_BayesDel_addAF_pred,dbNSFP_ExAC_AF,dbNSFP_Polyphen2_HVAR_pred,dbNSFP_SIFT_pred,dbNSFP_FATHMM_pred,dbNSFP_SIFT4G_pred,dbNSFP_LRT_pred,dbNSFP_fathmmXF_coding_pred,dbNSFP_BayesDel_noAF_pred,dbNSFP_gnomAD_exomes_AF,dbNSFP_Aloft_pred,dbNSFP_MutationTaster_pred,dbNSFP_MetaLR_pred,dbNSFP_LISTS2_pred,dbNSFP_Polyphen2_HDIV_pred,dbNSFP_MutationAssessor_pred,VariantEffect_EFF,Risco_Mut_EFF,Tipo_Mut_EFF,Point_Mutation_EFF,changeProt_EFF,changecDNA_EFF,Gene_EFF,RefSeq_EFF,Exon_EFF,Pos_Point_Mutation_EFF,poschangecDNA_EFF,typechangecDNA_EFF,aminBefore,aminAfter,poschangeProt,typechangeProt,SNP_ID_COMMON,COMMON,PolyPhen2_Dam_pred,Ndamage,NdamageCalc,Deleteria,Deleteria5,Deleteria10,Uniprot_id,PDB_id,Resolution,Swiss-Prot,db_align_beg,db_align_end,pdbx_auth_seq_align_beg,pdbx_auth_seq_align_end,pdbx_strand_id,seq_align_beg,seq_align_end,db_name,pdbx_align_begin,pdbx_seq_one_letter_code,len_seq,Blosum62,groupBefore,groupAfter,groupChange,aminBeforeEssential,aminAfterEssential,essencialChange,substitution,NodeId_RING,Dssp_RING,Degree_RING,Bfactor_CA_RING,Inter_Lig_tot,Inter_Res_tot,Inter_IAC_Lig_tot,Inter_VDW_Lig_tot,Inter_VDW_Res_tot,Inter_HBOND_Res_tot,Inter_PIPISTACK_Res_tot,Inter_IONIC_Res_tot,Inter_SSBOND_Res_tot,Inter_PICATION_Res_tot,triangles_node,clusteringCoef_node,betweennessWeighted_node,Tecido,Deleteria11
0,1,40292580,G,A,Peptidase_M48,T,T,D,T,N,T,D,T,0.000025,B,T,T,T,D,D,T,0.000012,.,D,T,D,P,N,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,Gtt/Att,p.Val447Ile,c.1339G>A,ZMPSTE24,NM_005857.4,10,1,1339,>,Val,Ile,447,subst,rs748601004,0.0,1,7/20,7,1,1,0,O75844,5SYT,2.00,FACE1_HUMAN,1.0,474.0,1.0,474.0,A,1.0,474.0,UNP,1,MGMWASLDALWEMPAEKRIFGAVLLFSWTVYLWETFLAQRQRRIYK...,479.0,3,nonpolar,nonpolar,nonpolarTOnonpolar,1,1,1TO1,0,A:447:_:VAL,,2.0,39.45,0.0,2.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.000000,0.000000,ACC,0
1,1,40406739,C,T,.,T,D,D,D,D,D,D,D,0.000008,D,D,T,D,D,D,D,0.000004,.,D,D,D,D,H,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,cCg/cTg,p.Pro36Leu,c.107C>T,SMAP2,NM_022733.2,2,2,107,>,Pro,Leu,36,subst,rs759545887,0.0,1,17/20,17,1,1,1,Q8WU79,2IQJ,1.90,SMAP2_HUMAN,1.0,132.0,1.0,132.0,A,3.0,134.0,UNP,1,-,0.0,-3,nonpolar,nonpolar,nonpolarTOnonpolar,0,1,0TO1,0,A:36:_:PRO,,21.0,23.19,16.0,5.0,16.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.019048,0.017387,ACC,1
2,1,56949695,G,A,Membrane_attack_complex_component/perforin_(MA...,T,T,N,T,N,T,T,T,0.000264,P,D,T,T,N,N,T,0.000223,.,N,T,T,D,.,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,Cgc/Tgc,p.Arg242Cys,c.724C>T,C8B,NM_000066.3,6,1,724,>,Arg,Cys,242,subst,rs150146785,1.0,1,2/20,2,0,0,0,P07358,3OJY,2.51,CO8B_HUMAN,55.0,591.0,1.0,537.0,B,1.0,537.0,UNP,55,SVDVTLMPIDCELSSWSSWTTCDPCQKKRYRYAYLLQPSQFHGEPC...,543.0,-3,positivecharge,polar,positivechargeTOpolar,0,0,0TO0,0,B:242:_:ARG,E,4.0,42.32,0.0,4.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.001848,ACC,0
3,1,155268782,C,T,.,T,T,D,T,N,T,D,T,0.000000,B,T,T,T,D,D,T,0.000000,.,D,T,.,B,M,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,cGg/cAg,p.Arg138Gln,c.413G>A,CLK2,NM_001294338.1,4,2,413,>,Arg,Gln,138,subst,rs1477026654,0.0,0,5/20,5,0,0,0,P49760,6FYK,2.39,CLK2_HUMAN,136.0,496.0,136.0,496.0,A,3.0,363.0,UNP,136,SSRRAKSVEDDAEGHLIYHVGDWLQERYEIVSTLGEGTFGRVVQCV...,365.0,1,positivecharge,polar,positivechargeTOpolar,0,0,0TO0,0,A:138:_:ARG,,4.0,40.34,0.0,4.0,0.0,0.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,0.000000,0.001240,ACC,0
4,1,156528563,G,A,"RasGAP_protein,_C-terminal",T,T,D,T,D,T,D,T,0.000008,D,D,T,T,D,D,T,0.000004,.,D,T,D,D,M,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,gCt/gTt,p.Ala1540Val,c.4619C>T,IQGAP3,NM_178229.4,36,2,4619,>,Ala,Val,1540,subst,rs764657941,0.0,1,9/20,9,1,1,0,Q86VI3,3ISU,1.88,IQGA3_HUMAN,1529.0,1631.0,1529.0,1631.0,A,19.0,121.0,UNP,1529,GKKQPSLHYTAAQLLEKGVLVEIEDLPASHFRNVIFDITPGDEAGK...,104.0,0,nonpolar,nonpolar,nonpolarTOnonpolar,0,1,0TO1,0,A:1540:_:ALA,H,6.0,20.70,0.0,6.0,0.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.029384,ACC,0
5,2,73830885,C,T,.,T,T,D,T,D,T,T,T,0.000033,B,D,T,D,D,D,T,0.000052,.,D,T,T,B,L,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,cCg/cTg,p.Pro10Leu,c.29C>T,STAMBP,NM_006463.4,3,2,29,>,Pro,Leu,10,subst,rs767316172,0.0,0,7/20,7,1,1,0,O95630,2XZE,1.75,STABP_HUMAN,1.0,146.0,1.0,146.0,A,1.0,146.0,UNP,-,-,0.0,-3,nonpolar,nonpolar,nonpolarTOnonpolar,0,1,0TO1,0,A:10:_:PRO,,2.0,31.63,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000290,ACC,0
6,2,74887977,G,T,"Hexokinase,_C-terminal",D,D,D,D,D,D,D,D,0.000000,D,D,D,D,D,D,D,0.000008,.,D,D,D,D,M,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,gGa/gTa,p.Gly765Val,c.2294G>T,HK2,NM_000189.4,16,2,2294,>,Gly,Val,765,subst,rs1264600281,0.0,1,18/20,18,1,1,1,P52789,2NZT,2.45,HXK2_HUMAN,17.0,916.0,17.0,916.0,A,3.0,902.0,UNP,17,DQVQKVDQYLYHMRLSDETLLEISKRFRKEMEKGLGATTHPTAAVK...,911.0,-3,nonpolar,nonpolar,nonpolarTOnonpolar,0,1,0TO1,1,A:765:_:GLY,H,1.0,54.42,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,ACC,1
7,2,96296982,T,C,DEAD/DEAH_box_helicase_domain|Helicase_superfa...,T,T,D,T,D,T,T,T,0.000000,B,T,T,T,N,N,T,0.000004,.,D,T,D,B,M,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,tAc/tGc,p.Tyr489Cys,c.1466A>G,SNRNP200,NM_014014.4,12,2,1466,>,Tyr,Cys,489,subst,rs1259944697,0.0,0,4/20,4,1,0,0,O75643,6S8Q,2.39,U520_HUMAN,394.0,2136.0,394.0,2136.0,B,5.0,1747.0,UNP,394,MDLDQGGEALAPRQVLDLEDLVFTQGSHFMANKRCQLPDGSFRRQR...,1764.0,-2,aromatic,polar,aromaticTOpolar,0,0,0TO0,0,B:489:_:TYR,H,20.0,35.19,0.0,20.0,0.0,0.0,17.0,3.0,0.0,0.0,0.0,0.0,6.0,0.031579,0.003900,ACC,0
8,1,114713909,G,T,P-loop_containing_nucleoside_triphosphate_hydr...,D,D,D,D,D,D,D,D,0.000000,P,D,D,D,U,D,D,0.000000,.,D,D,D,P,M,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,Caa/Aaa,p.Gln61Lys,c.181C>A,NRAS,NM_002524.4,3,1,181,>,Gln,Lys,61,subst,rs121913254,0.0,1,17/20,17,1,1,1,P01111,5UHV,1.67,RASN_HUMAN,1.0,166.0,1.0,166.0,A,1.0,166.0,UNP,1,MTEYKLVVVGAGGVGKSALTIQLIQNHFVDEYDPTIEDSYRKQVVI...,168.0,1,polar,positivecharge,polarTOpositivecharge,0,1,0TO1,1,A:61:_:GLN,S,22.0,41.02,20.0,2.0,20.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,ACC,1
9,1,211673529,G,A,Protein_kinase_domain|Protein_kinase-like_domain,T,T,D,T,D,D,D,D,0.000000,D,D,T,D,D,D,D,0.000004,.,D,T,D,D,L,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,aCg/aTg,p.Thr170Met,c.509C>T,NEK2,NM_002497.3,3,2,509,>,Thr,Met,170,subst,rs759517583,0.0,1,13/20,13,1,1,1,P51955,2W5A,1.55,NEK2_HUMAN,1.0,271.0,1.0,271.0,A,1.0,271.0,UNP,-,-,0.0,-1,polar,nonpolar,polarTOnonpolar,1,1,1TO1,0,A:170:_:THR,S,9.0,69.16,1.0,8.0,1.0,0.0,6.0,2.0,0.0,0.0,0.0,0.0,2.0,0.055556,0.044739,ACC,1
26883,13,113118613,G,A,"Peptidase_S1,_PA_clan|Serine_proteases,_trypsi...",T,T,N,T,N,D,T,T,0.000025,P,D,D,T,N,N,T,0.000016,.,N,D,D,D,L,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,Gtg/Atg,p.Val336Met,c.1006G>A,F7,NM_000131.4,9,1,1006,>,Val,Met,336,subst,rs374305125,0.0,1,6/20,6,1,1,0,P08709,5PAG,1.36,FA7_HUMAN,213.0,466.0,213.0,466.0,B,1.0,254.0,UNP,149,LICVNENGGCEQYCSDHTGTKRSCRCHEGYSLLADGVSCTPTVEYP...,64.0,1,nonpolar,nonpolar,nonpolarTOnonpolar,1,1,1TO1,0,B:336:_:VAL,,4.0,23.17,0.0,4.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,UVM,0
26884,15,40298224,T,C,"PLC-like_phosphodiesterase,_TIM_beta/alpha-bar...",T,T,D,T,N,T,D,T,0.000008,P,T,T,T,D,D,T,0.000005,.,D,T,D,P,N,NON_SYNONYMOUS_CODING+SPLICE_SITE_REGION,MODERATE,MISSENSE,aAa/aGa,p.Lys385Arg,c.1154A>G,PLCB2,NM_004573.2,11,2,1154,>,Lys,Arg,385,subst,rs769251460,0.0,1,7/20,7,1,1,0,Q00722,2ZKM,1.62,PLCB2_HUMAN,1.0,799.0,1.0,799.0,X,1.0,799.0,UNP,1,MSLLNPVLLPPKVKAYLSQGERFIKWDDETTVASPVILRVDPKGYY...,808.0,2,positivecharge,positivecharge,positivechargeTOpositivecharge,1,0,1TO0,0,X:385:_:LYS,H,10.0,9.86,0.0,10.0,0.0,0.0,8.0,2.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.004958,UVM,0
26885,15,40298938,G,A,EF-hand_domain_pair|Phosphoinositide-specific_...,D,T,D,T,D,D,D,D,0.000000,P,D,T,D,D,D,D,0.000004,.,D,T,D,D,M,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,aCg/aTg,p.Thr237Met,c.710C>T,PLCB2,NM_004573.2,9,2,710,>,Thr,Met,237,subst,rs1242886355,0.0,1,14/20,14,1,1,1,Q00722,2ZKM,1.62,PLCB2_HUMAN,1.0,799.0,1.0,799.0,X,1.0,799.0,UNP,1,MSLLNPVLLPPKVKAYLSQGERFIKWDDETTVASPVILRVDPKGYY...,808.0,-1,polar,nonpolar,polarTOnonpolar,1,1,1TO1,0,X:237:_:THR,,1.0,45.91,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,UVM,1
26886,17,4819482,G,A,Phospholipase_D-like_domain,T,T,D,T,D,T,D,D,0.000000,D,D,T,D,D,D,D,0.000000,.,D,T,D,D,H,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,Gcc/Acc,p.Ala788Thr,c.2362G>A,PLD2,NM_002663.4,23,1,2362,>,Ala,Thr,788,subst,rs779094449,0.0,1,13/20,13,1,1,1,O14939,6OHM,1.90,PLD2_HUMAN,294.0,933.0,294.0,933.0,A,1.0,640.0,UNP,294,SSYRQARWWAQEITELAQGPGRDFLQLHRHDSYAPPRPGTLARWFV...,648.0,0,nonpolar,polar,nonpolarTOpolar,0,1,0TO1,0,A:788:_:ALA,E,5.0,12.52,0.0,5.0,0.0,0.0,3.0,2.0,0.0,0.0,0.0,0.0,1.0,0.100000,0.003741,UVM,1
26887,17,75573209,C,T,WD40/YVTN_repeat-like-containing_domain,T,T,D,T,D,T,D,T,0.000025,D,D,T,D,D,D,T,0.000032,.,D,T,D,D,M,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,Cgc/Tgc,p.Arg886Cys,c.2656C>T,LLGL2,NM_001031803.1,20,1,2656,>,Arg,Cys,886,subst,rs370466207,0.0,1,10/20,10,1,1,1,Q6P1M3,6N8R,1.91,L2GL2_HUMAN,13.0,978.0,13.0,978.0,A,2.0,967.0,UNP,13,RERLKRDLFQFNKTVEHGFPHQPSALGYSPSLRILAIGTRSGAIKL...,978.0,-3,positivecharge,polar,positivechargeTOpolar,0,0,0TO0,0,A:886:_:ARG,E,9.0,12.64,0.0,9.0,0.0,0.0,7.0,2.0,0.0,0.0,0.0,0.0,1.0,0.027778,0.000024,UVM,0
26888,17,82032779,C,T,P-loop_containing_nucleoside_triphosphate_hydr...,D,D,D,D,D,D,D,D,0.000000,P,D,D,D,D,D,D,0.000000,.,D,D,T,D,H,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,gCg/gTg,p.Ala59Val,c.176C>T,RAC3,NM_005052.2,3,2,176,>,Ala,Val,59,subst,rs1379395211,0.0,1,18/20,18,1,1,1,P60763,2QME,1.75,RAC3_HUMAN,1.0,177.0,1.0,177.0,A,2.0,178.0,UNP,1,MQAIKCVVVGDGAVGKTCLLISYTTNAFPGEYIPTVFDNYSANVMV...,179.0,0,nonpolar,nonpolar,nonpolarTOnonpolar,0,1,0TO1,0,A:59:_:ALA,,57.0,22.18,52.0,5.0,52.0,0.0,4.0,1.0,0.0,0.0,0.0,0.0,5.0,0.003133,0.020405,UVM,1
26889,18,57357044,G,A,.,T,T,D,T,N,T,T,T,0.000255,B,T,T,T,D,D,T,0.000235,.,D,T,D,P,L,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,cGg/cAg,p.Arg145Gln,c.434G>A,ST8SIA3,NM_015879.2,3,2,434,>,Arg,Gln,145,subst,rs201032971,0.0,1,6/20,6,0,0,0,O43173,5BO7,1.85,SIA8C_HUMAN,81.0,380.0,81.0,380.0,A,24.0,323.0,UNP,81,QELQEKPSKWKFNRTAFLHQRQEILQHVDVIKNFSLTKNSVRIGQL...,303.0,1,positivecharge,polar,positivechargeTOpolar,0,0,0TO0,0,A:145:_:ARG,H,10.0,24.34,0.0,10.0,0.0,0.0,4.0,6.0,0.0,0.0,0.0,0.0,3.0,0.066667,0.027366,UVM,0
26890,22,37232820,G,A,P-loop_containing_nucleoside_triphosphate_hydr...,D,D,D,D,D,D,D,D,0.000000,D,D,T,D,D,D,D,0.000000,.,D,D,T,D,H,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,cCg/cTg,p.Pro69Leu,c.206C>T,RAC2,NM_002872.4,3,2,206,>,Pro,Leu,69,subst,rs1443752435,0.0,1,17/20,17,1,1,1,P15153,2W2X,2.30,RAC2_HUMAN,2.0,179.0,2.0,179.0,A,8.0,185.0,UNP,-,-,0.0,-3,nonpolar,nonpolar,nonpolarTOnonpolar,0,1,0TO1,0,A:69:_:PRO,H,7.0,43.47,0.0,7.0,0.0,0.0,6.0,1.0,0.0,0.0,0.0,0.0,1.0,0.047619,0.004729,UVM,1
26891,17,81956919,G,A,.,T,T,D,T,N,D,T,T,0.000157,P,D,.,D,D,D,T,0.000100,.,D,T,D,D,M,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,aCg/aTg,p.Thr284Met,c.851C>T,NOTUM,NM_178493.5,7,2,851,>,Thr,Met,284,subst,rs138384810,1.0,1,9/20,9,0,0,0,Q6P988,4UZQ,1.50,NOTUM_HUMAN,81.0,451.0,81.0,451.0,A,4.0,374.0,UNP,-,-,0.0,-1,polar,nonpolar,polarTOnonpolar,1,1,1TO1,0,A:284:_:THR,G,21.0,9.73,14.0,7.0,14.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,2.0,0.009524,0.011636,UVM,0
26892,19,41088938,C,T,.,T,T,N,T,D,T,T,T,0.000033,B,D,T,D,U,N,T,0.000044,.,N,T,T,B,M,NON_SYNONYMOUS_CODING,MODERATE,MISSENSE,Cgc/Tgc,p.Arg64Cys,c.190C>T,CYP2A13,NM_000766.4,2,1,190,>,Arg,Cys,64,subst,rs72547586,0.0,0,3/20,3,0,0,0,Q16696,4EJI,2.10,CP2AD_HUMAN,31.0,494.0,31.0,494.0,A,9.0,472.0,UNP,31,GKLPPGPTPLPFIGNYLQLNTEQMYNSLMKISERYGPVFTIHLGPR...,469.0,-3,positivecharge,polar,positivechargeTOpolar,0,0,0TO0,0,A:64:_:ARG,H,2.0,44.90,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000658,UVM,0

In [38]:
df.describe()

,CHROM,POS,dbNSFP_ExAC_AF,dbNSFP_gnomAD_exomes_AF,Exon_EFF,Pos_Point_Mutation_EFF,poschangecDNA_EFF,poschangeProt,COMMON,PolyPhen2_Dam_pred,NdamageCalc,Deleteria,Deleteria5,Deleteria10,Resolution,db_align_beg,db_align_end,pdbx_auth_seq_align_beg,pdbx_auth_seq_align_end,seq_align_beg,seq_align_end,len_seq,aminBeforeEssential,substitution,Degree_RING,Bfactor_CA_RING,Inter_Lig_tot,Inter_Res_tot,Inter_IAC_Lig_tot,Inter_VDW_Lig_tot,Inter_VDW_Res_tot,Inter_HBOND_Res_tot,Inter_PIPISTACK_Res_tot,Inter_IONIC_Res_tot,Inter_SSBOND_Res_tot,Inter_PICATION_Res_tot,triangles_node,clusteringCoef_node,betweennessWeighted_node,Deleteria11
count,26893.000000,2.689300e+04,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000,26893.000000
mean,9.853493,7.559061e+07,0.000032,0.000031,8.083702,1.500688,1060.496672,353.998661,0.018592,0.758525,11.047410,0.769494,0.752984,0.591009,1.914777,190.667125,519.370803,188.095118,517.623731,7.232105,335.562637,284.648942,0.196817,0.115867,19.927007,32.120029,14.025025,5.903469,13.986391,0.038635,3.238352,2.518648,0.030640,0.103521,0.000892,0.011416,1.539360,0.043939,0.015648,0.543450
std,6.359959,5.831963e+07,0.000173,0.000166,7.234838,0.568498,1146.910524,382.308396,0.135082,0.427986,5.690707,0.421165,0.431284,0.491657,0.370304,368.221183,400.117986,365.497012,398.641507,25.871623,207.602516,232.988473,0.397600,0.320071,53.131619,20.790585,52.903412,4.179669,52.761158,0.351092,3.422655,1.745289,0.229852,0.319771,0.029861,0.106584,2.575612,0.106151,0.032348,0.498118
min,1.000000,7.966600e+04,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.730000,0.000000,15.000000,-16.000000,15.000000,1.000000,6.000000,0.000000,0.000000,0.000000,1.000000,0.700000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.000000,3.046701e+07,0.000000,0.000000,3.000000,1.000000,397.000000,133.000000,0.000000,1.000000,7.000000,1.000000,1.000000,0.000000,1.650000,2.000000,293.000000,2.000000,293.000000,1.000000,198.000000,130.000000,0.000000,0.000000,3.000000,17.060000,0.000000,3.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000107,0.000000
50%,10.000000,6.231222e+07,0.000008,0.000004,6.000000,1.000000,736.000000,246.000000,0.000000,1.000000,12.000000,1.000000,1.000000,1.000000,1.900000,41.000000,411.000000,40.000000,412.000000,2.000000,297.000000,256.000000,0.000000,0.000000,6.000000,27.490000,0.000000,5.000000,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000335,0.004557,1.000000
75%,16.000000,1.127550e+08,0.000017,0.000020,10.000000,2.000000,1298.000000,433.000000,0.000000,1.000000,16.000000,1.000000,1.000000,1.000000,2.200000,220.000000,620.000000,216.000000,620.000000,5.000000,417.000000,390.000000,0.000000,0.000000,11.000000,41.620000,0.000000,8.000000,0.000000,0.000000,5.000000,4.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.047619,0.016700,1.000000
max,22.000000,2.474191e+08,0.009661,0.008633,146.000000,3.000000,26362.000000,8788.000000,1.000000,1.000000,20.000000,1.000000,1.000000,1.000000,2.590000,8769.000000,8797.000000,8769.000000,8797.000000,652.000000,1747.000000,3475.000000,1.000000,1.000000,1208.000000,206.930000,1207.000000,37.000000,1204.000000,16.000000,34.000000,12.000000,5.000000,3.000000,1.000000,2.000000,63.000000,1.000000,0.511033,1.000000

In [44]:
# dbNSFP pathogenicity predictors
DBNSFP_PREDICTOR_COLS = [c for c in df.columns if c.startswith("dbNSFP_") and c.endswith("_pred")]

print(len(DBNSFP_PREDICTOR_COLS))

# '.' encodes missing values 
# so we need to pass then as nan cause pandas' dumb :D
missing_predicators = (
    df[DBNSFP_PREDICTOR_COLS]
    .replace('.', np.nan)
    .isna()
    .mean()
    .sort_values(ascending=False))

print(missing_predicators[missing_predicators > 0].to_string())

21
dbNSFP_Aloft_pred               0.934593
dbNSFP_FATHMM_pred              0.035771
dbNSFP_MutationAssessor_pred    0.034358
dbNSFP_LRT_pred                 0.028818
dbNSFP_LISTS2_pred              0.023277
dbNSFP_PrimateAI_pred           0.011155
dbNSFP_MCAP_pred                0.004090
dbNSFP_SIFT4G_pred              0.003793
dbNSFP_fathmmXF_coding_pred     0.003309
dbNSFP_DEOGEN2_pred             0.002491
dbNSFP_MutationTaster_pred      0.001190
dbNSFP_MetaSVM_pred             0.000409
dbNSFP_MetaLR_pred              0.000409
dbNSFP_ClinPred_pred            0.000409

In [45]:
predicators_vocab = { col: sorted(df[col].astype(str).unique()) for col in DBNSFP_PREDICTOR_COLS }

print('\n\n')
for col, vocab in predicators_vocab.items():
    print(f"{col:<32} {vocab}")

dbNSFP_DEOGEN2_pred              ['.', 'D', 'T']
dbNSFP_MetaSVM_pred              ['.', 'D', 'T']
dbNSFP_fathmmMKL_coding_pred     ['D', 'N']
dbNSFP_PrimateAI_pred            ['.', 'D', 'T']
dbNSFP_PROVEAN_pred              ['D', 'N']
dbNSFP_MCAP_pred                 ['.', 'D', 'T']
dbNSFP_ClinPred_pred             ['.', 'D', 'T']
dbNSFP_BayesDel_addAF_pred       ['D', 'T']
dbNSFP_Polyphen2_HVAR_pred       ['B', 'D', 'P']
dbNSFP_SIFT_pred                 ['D', 'T']
dbNSFP_FATHMM_pred               ['.', 'D', 'T']
dbNSFP_SIFT4G_pred               ['.', 'D', 'T']
dbNSFP_LRT_pred                  ['.', 'D', 'N', 'U']
dbNSFP_fathmmXF_coding_pred      ['.', 'D', 'N']
dbNSFP_BayesDel_noAF_pred        ['D', 'T']
dbNSFP_Aloft_pred                ['.', 'Dominant']
dbNSFP_MutationTaster_pred       ['.', 'A', 'D', 'N']
dbNSFP_MetaLR_pred               ['.', 'D', 'T']
dbNSFP_LISTS2_pred               ['.', 'D', 'T']
dbNSFP_Polyphen2_HDIV_pred       ['B', 'D', 'P']
dbNSFP_MutationAssessor_pred     ['.', 'H', 'L', 'M', 'N']

O **dbNSFP** (database for nonsynonymous SNP's functional predicators) é um banco de dados
que agrega, pra cada variante _missense_ conhecida, as predições de **patogenicidade** produzida por ferramentas computacionais independentes.
Como cada ferramenta é treinada/calibrada (etc etc) com ferramentas distintas com trade-offs diferentes, isoladamente não são perfeitas, mas em conjunto, quando a maioria converge pra um _deletério_, a evidência é mais sólida do que qualquer preditor isolado

| Code | Meaning |
| ---- | ------- |
| D | Damaging |
| T | Tolerated |
| N | Neutral | 
| B | Benign | 
| P | Possibly damaging |